[package]
name = "rda5807m"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-hal = "0.2.7"

[dev-dependencies]
embedded-hal-mock = { version = "0.10", default-features = false, features = ["eh0"] }